# -*- coding: utf-8 -*-
"""Employees- System-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPZ5rTnoofAp1pdf0ehWSIRIuUlVFqoo
"""

# Employees-System-Project

# Employee Class

class Employee:
    def __init__(self, name, age, salary):
        self.name = name
        self.age = age
        self.salary = salary

    def __str__(self):
        return f"Name: {self.name}, Age: {self.age}, Salary: {self.salary}"


# Employees Manager Class

class EmployeesManager:
    def __init__(self):
        self.employees = []

    def add_employee(self, name, age, salary):
        emp = Employee(name, age, salary)
        self.employees.append(emp)

    def list_employees(self):
        if not self.employees:
            print("No employees found")
        for emp in self.employees:
            print(emp)

    def delete_by_age(self, min_age, max_age):
        self.employees = [emp for emp in self.employees if not (min_age <= emp.age <= max_age)]
        print("Employees deleted in given age range")

    def find_by_name(self, name):
        for emp in self.employees:
            if emp.name == name:
                print(emp)
                return
        print("Employee not found")

    def update_salary(self, name, new_salary):
        for emp in self.employees:
            if emp.name == name:
                emp.salary = new_salary
                print("Salary updated")
                return
        print("Employee not found")


# Frontend Manager Class
class FrontendManager:
    def __init__(self):
        self.manager = EmployeesManager()       # Creates an object of EmployeesManager

    def menu(self):
        while True:
            print("\n1. Add Employee")
            print("2. List Employees")
            print("3. Delete by Age Range")
            print("4. Update Salary")
            print("5. Exit")

            choice = input("Enter choice: ")

            if choice == "1":
                name = input("Enter name: ")
                age = int(input("Enter age: "))
                salary = float(input("Enter salary: "))
                self.manager.add_employee(name, age, salary)

            elif choice == "2":
                self.manager.list_employees()

            elif choice == "3":
                min_age = int(input("Enter min age: "))
                max_age = int(input("Enter max age: "))
                self.manager.delete_by_age(min_age, max_age)


            elif choice == "4":
                name = input("Enter name: ")
                salary = float(input("Enter new salary: "))
                self.manager.update_salary(name, salary)




            elif choice == "5":
                print("Exit")
                break

            # else:
            #     print("Invalid choice")


# Run Program
app = FrontendManager()
app.menu()