# -*- coding: utf-8 -*-
"""Hospital-Patient-Management-System Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-sLOEt9tJ8IVPnJr65MriscusihcjMLm
"""

# Hospital Patient Queue Management System

# Patient Class

class Patient:
    def __init__(self, name, status):
        self.name = name
        self.status = status   # 0 = normal, 1 = urgent, 2 = super urgent

# defines how an object looks when printed
    def __str__(self):
        return f"{self.name} (Status: {self.status})"


# Specialization Class
class Specialization:
    def __init__(self, name):
        self.name = name
        self.queue = []

    def add_patient(self, patient):
        # Add based on priority (higher status first)
        if patient.status == 2:
            self.queue.insert(0, patient)
        elif patient.status == 1:
            self.queue.insert(0, patient)
        else:
            self.queue.append(patient)

    def get_next_patient(self):
        if self.queue:
            return self.queue.pop(0)
        else:
            return None

    def remove_patient(self, name):
        for p in self.queue:
            if p.name == name:
                self.queue.remove(p)
                return True
        return False

    def list_patients(self):
        if not self.queue:
            print("No patients in this specialization")
        for p in self.queue:
            print(p)


# Operations Manager Class
class OperationsManager:
    def __init__(self):
        self.specializations = {
            "General": Specialization("General"),
            "Cardiology": Specialization("Cardiology"),
            "Orthopedic": Specialization("Orthopedic")
        }

    def menu(self):
        while True:
            print("\n1. Add Patient")
            print("2. List Patients")
            print("3. Get Next Patient")
            print("4. Remove Patient")
            print("5. Exit")

            choice = input("Enter choice: ")

            if choice == "1":
                spec = input("Enter specialization (General/Cardiology/Orthopedic): ")
                name = input("Enter patient name: ")
                status = int(input("Enter status (0=Normal, 1=Urgent, 2=Super Urgent): "))

                if spec in self.specializations:
                    patient = Patient(name, status)
                    self.specializations[spec].add_patient(patient)
                else:
                    print("Invalid specialization")

            elif choice == "2":
                for spec, obj in self.specializations.items():
                    print(f"\n{spec}:")
                    obj.list_patients()

            elif choice == "3":
                spec = input("Enter specialization: ")
                if spec in self.specializations:
                    patient = self.specializations[spec].get_next_patient()
                    if patient:
                        print("Next patient:", patient)
                    else:
                        print("No patients")
                else:
                    print("Invalid specialization")

            elif choice == "4":
                spec = input("Enter specialization: ")
                name = input("Enter patient name: ")

                if spec in self.specializations:
                    removed = self.specializations[spec].remove_patient(name)
                    if removed:
                        print("Patient removed")
                    else:
                        print("Patient not found")
                else:
                    print("Invalid specialization")

            elif choice == "5":
                print("Exiting...")
                break

            else:
                print("Invalid choice")


# Run Program
app = OperationsManager()
app.menu()