# -*- coding: utf-8 -*-
"""Exception-handling-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLikkEKvufjObHPR6SSONmNq61eQKqRZ
"""

# 1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.


try:
    num1 = int(input("Enter numerator: "))
    num2 = int(input("Enter denominator: "))

    result = num1 / num2
    print("Result:", result)

except ZeroDivisionError:
    print("Error: Cannot divide by zero ")

#2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer.

try:
    user_input = input("Enter an integer: ")
    number = int(user_input)   # This will raise ValueError if input is invalid
    print("You entered:", number)

except ValueError:
    print("Error: That is not a valid integer!")

# 3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.

try:
  with open('sampl.txt','r') as f:
    print(f.read())
except FileNotFoundError:
  print('file does not exist.')

#4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical.

try:
    num1 = input("Enter first number: ")
    num2 = input("Enter second number: ")

 # Try converting inputs to float
    num1 = float(num1)
    num2 = float(num2)

    print("Sum:", num1 + num2)

except ValueError:
    print("Error: Input must be numerical values")

# 5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.

try:
    with open("sample.txt", "r") as file:
        print(file.read())

except PermissionError:
    print("Error: Permission denied. Cannot access the file.")

except FileNotFoundError:
    print("Error: File  not found.")

# 6. Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.

try:
    lst = [10, 20, 30]

    print(lst[5])

except IndexError:
    print("Error: Index is out of range.")

# 7. Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.

try:
    a = 10
    b = 0

    result = a / b
    print(result)

except ArithmeticError:
    print("Error: Arithmetic error occurred.")