# -*- coding: utf-8 -*-
"""File-IO-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g51SjrgsyiLQu6KKckd9EzDXMCz0Vd8A
"""

# write a file
f = open('sample.txt','w')
f.write('Hello world')
f.write('\nHi')
f.write('\nGood Afternoon')
f.close()

# 1. Write a Python program to read an entire text file.

f = open("sample.txt", "r")   # open file in read mode
content = f.read()            # read entire file
print(content)                   # display content
f.close()                     # close file

# 2. Write a Python program to read first n lines of a file.

# Method - 1  -- readline

n = int(input("Enter number of lines: "))

with open("sample.txt", "r") as file:
    for i in range(n):
        line = file.readline()
        if not line:   # stop if file ends
            break
        print(line, end="")


# Method - 2  -- readlines

n = int(input("Enter number of lines: "))

with open("sample.txt", "r") as file:
    lines = file.readlines()
    for line in lines[:n]:
        print(line, end="")

# 3. Write a Python program to append text to a file and display the text.


f = open('sample.txt','a')
f.write('\nsachin')
f.write('\ntendulkar')
f.close()

# 4. Write a Python program to read last n lines of a file.

n = int(input("Enter number of lines: "))

with open("sample.txt", "r") as file:
    lines = file.readlines()
    for line in lines[-n:]:
        print(line, end="")

# 5. Write a Python program to read a file line by line and store it into a list.

lines_list = []

with open("sample.txt", "r") as file:
    for line in file:
        lines_list.append(line.strip())   # remove newline

print(lines_list)

# 6. Write a Python program to read a file line by line store it into a variable.

content = ""

with open("sample.txt", "r") as file:
    for line in file:
        content += line   # store each line in variable

print(content)

# 7. Write a python program to find the longest words.


with open("sample.txt", "r") as file:
    text = file.read()

words = text.split()

max_len = 0
longest_words = []

for word in words:
    if len(word) > max_len:
        max_len = len(word)
        longest_words = [word]
    elif len(word) == max_len:
        longest_words.append(word)

print("Longest word(s):", longest_words)
print("Length:", max_len)

# 8. Write a Python program to count the number of lines in a text file.

count = 0

with open("sample.txt", "r") as file:
    for line in file:
        count += 1

print("Number of lines:", count)

# 9. Write a Python program to count the frequency of words in a file.

with open("sample.txt", "r") as file:
    text = file.read().lower()   # convert to lowercase

words = text.split()   # split into words

freq = {}

for word in words:
    if word in freq:
        freq[word] += 1
    else:
        freq[word] = 1

print("Word Frequency:")
for word, count in freq.items():
    print(word, ":", count)

# 10. Write a Python program to get the file size of a plain file.

import os

file_path = "sample.txt"

size = os.path.getsize(file_path)

print("File Size:", size, "bytes")

# 11. Write a Python program to write a list to a file.

L = ['dhoni\n','raina\n','jadeja']
f = open('sample_1.txt','w')
f.writelines(L)
f.close()

# 12. Write a Python program to copy the contents of a file to another file .

with open("sample.txt", "r") as sam:
    content = sam.read()

with open("copied.txt", "w") as cop:
    cop.write(content)

print("File copied successfully ")

# 13. Write a Python program to read a random line from a file.

import random

with open("sample.txt", "r") as file:
    lines = file.readlines()

random_line = random.choice(lines)

print("Random Line:", random_line)

# 14. Write a Python program to assess if a file is closed or not.

file = open("sample.txt", "r")

print("Is file closed?", file.closed)   # False

file.close()

print("Is file closed?", file.closed)   # True

# 15.Write a Python program that takes a text file as input and returns the number of words of a given text file.

with open("sample.txt", "r") as file:
    text = file.read()

words = text.split()   # split into words

print("Number of words:", len(words))