# -*- coding: utf-8 -*-
"""oop-Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQcjrf1hO_O9DMJ4exmAzOKQmBflHKvF
"""

# 1. Write a Python program to create a class representing a Circle. Include methods to calculate its area and perimeter.
import math   # to use value of π (pi)

class Circle:
    def __init__(self, radius):              # It is a constructor method / #  __init__ is a special method (also called constructor)
        self.radius = radius

    def area(self):                         # A function defined inside a class is called a METHOD.
        return math.pi * self.radius ** 2   # πr²

    def perimeter(self):
        return 2 * math.pi * self.radius   # 2πr


# Create object
a = float(input("Enter the radius: "))
c1 = Circle(a)

# Call methods
print("Area:", c1.area())
print("Perimeter:", c1.perimeter())

# 2. Write a Python program to create a person class. Include attributes like name, country and date of birth. Implement a method to determine the person's age.

from datetime import date

class Person:
    def __init__(self, name, country, dob):
        self.name = name
        self.country = country
        self.dob = dob

    def calculate_age(self):
        today = date.today()

        age = today.year - self.dob.year

        if (today.month, today.day) < (self.dob.month, self.dob.day):
            age -= 1

        return age


p1 = Person("Bhavesh", "India", date(2000, 5, 15))    # date of birth (YYYY, MM, DD)

print("Name:", p1.name)
print("Country:", p1.country)
print("Age:", p1.calculate_age())

from datetime import date

class Person:
    def __init__(self, name, country, dob):
        self.name = name
        self.country = country
        self.dob = dob

    def calculate_age(self):
        today = date.today()
        age = today.year - self.dob.year

        if (today.month, today.day) < (self.dob.month, self.dob.day):
            age -= 1

        return age


#  Taking input from user
name = input("Enter your name: ")
country = input("Enter your country: ")

year = int(input("Enter birth year (YYYY): "))
month = int(input("Enter birth month (MM): "))
day = int(input("Enter birth day (DD): "))

# Create date object
dob = date(year, month, day)

# Create object
p1 = Person(name, country, dob)

# Output
print("\n--- Person Details ---")
print("Name:", p1.name)
print("Country:", p1.country)
print("Age:", p1.calculate_age())

# 3. Write a Python program to create a calculator class. Include methods for basic arithmetic operations.

class Calculator:

    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):
        if b == 0:
            return "Cannot divide by zero"
        return a / b


# Create object
calc = Calculator()

# Perform operations
print("Addition:", calc.add(10, 5))
print("Subtraction:", calc.subtract(10, 5))
print("Multiplication:", calc.multiply(10, 5))
print("Division:", calc.divide(10, 5))

calc = Calculator()

a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

print("Add:", calc.add(a, b))
print("Subtract:", calc.subtract(a, b))
print("Multiply:", calc.multiply(a, b))
print("Divide:", calc.divide(a, b))

# 4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter. Implement subclasses for different shapes like circle, triangle, and square.

import math

# Base Class
class Shape:
    def area(self):
        pass

    def perimeter(self):
        pass


# Circle Class            # subclass
class Circle(Shape):      # inheritance
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * self.radius ** 2      # πr²

    def perimeter(self):
        return 2 * math.pi * self.radius        # 2πr

#  Square Class             # subclass
class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side * self.side        # side * side

    def perimeter(self):
        return 4 * self.side                #  4 * side


# Triangle Class              # subclass
class Triangle(Shape):
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c

    def perimeter(self):
        return self.a + self.b + self.c

    def area(self):
        s = self.perimeter() / 2   # semi-perimeter
        return (s * (s - self.a) * (s - self.b) * (s - self.c)) ** 0.5


#  Create Objects c,s,t
c = Circle(5)
s = Square(4)
t = Triangle(3, 4, 5)

# 🔹 Output
print("Circle Area:", c.area())
print("Circle Perimeter:", c.perimeter())

print("Square Area:", s.area())
print("Square Perimeter:", s.perimeter())

print("Triangle Area:", t.area())
print("Triangle Perimeter:", t.perimeter())

# skip bola hain sir ne
# 5. Write a Python program to create a class representing a binary search tree. Include methods for inserting and searching for elements in the binary tree.

# Node class (each element of tree)
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None


#  Binary Search Tree class
class BST:
    def __init__(self):
        self.root = None

    # Insert method
    def insert(self, value):
        if self.root is None:
            self.root = Node(value)
        else:
            self._insert(self.root, value)

    def _insert(self, current, value):
        if value < current.value:
            if current.left is None:
                current.left = Node(value)
            else:
                self._insert(current.left, value)
        else:
            if current.right is None:
                current.right = Node(value)
            else:
                self._insert(current.right, value)

    #  Search method
    def search(self, value):
        return self._search(self.root, value)

    def _search(self, current, value):
        if current is None:
            return False
        if current.value == value:
            return True
        elif value < current.value:
            return self._search(current.left, value)
        else:
            return self._search(current.right, value)


#  Create BST
tree = BST()

# Insert values
tree.insert(50)
tree.insert(30)
tree.insert(70)
tree.insert(20)
tree.insert(40)
tree.insert(60)
tree.insert(80)

# Search values
print("Search 40:", tree.search(40))
print("Search 90:", tree.search(90))

# 6. Write a Python program to create a class representing a stack data structure. Include methods for pushing and popping elements.
# Stack Class
class Stack:
    def __init__(self):
        self.items = []   # empty list to store elements

    #  Push (add element)
    def push(self, item):
        self.items.append(item)
        print(item, "pushed into stack")

    # Pop (remove element)
    def pop(self):
        if len(self.items) == 0:
            print("Stack is empty")
        else:
            removed = self.items.pop()
            print(removed, "popped from stack")

    #  Display stack
    def display(self):
        print("Stack:", self.items)


#  Create stack object
s = Stack()

#  Operations
s.push(10)
s.push(20)
s.push(30)

s.display()

s.pop()
s.display()

# 7. Write a Python program to create a class representing a linked list data structure. Include methods for displaying linked list data, inserting and deleting nodes.

# Node class
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


#  Linked List class
class LinkedList:
    def __init__(self):
        self.head = None

    #  Insert at end
    def insert(self, data):
        new_node = Node(data)

        if self.head is None:
            self.head = new_node
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = new_node

    #  Display list
    def display(self):
        temp = self.head
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")

    #  Delete a node
    def delete(self, value):
        temp = self.head

        # If head needs to be deleted
        if temp and temp.data == value:
            self.head = temp.next
            temp = None
            return

        # Search for node
        prev = None
        while temp and temp.data != value:
            prev = temp
            temp = temp.next

        # If value not found
        if temp is None:
            print("Value not found")
            return

        # Delete node
        prev.next = temp.next
        temp = None


#  Create linked list
ll = LinkedList()

# Insert elements
ll.insert(10)
ll.insert(20)
ll.insert(30)
ll.insert(40)

# Display
print("Linked List:")
ll.display()

# Delete node
ll.delete(20)

print("After deletion:")
ll.display()

# 8. Write a Python program to create a class representing a shopping cart. Include methods for adding and removing items, and calculating the total price.

class ShoppingCart:

    def __init__(self):
        self.items = {}   # dictionary to store items {item: price}

    #  Add items
    def add_item(self, name, price):
        self.items[name] = price
        print(name, "added to cart")

    # Remove items
    def remove_item(self, name):
        if name in self.items:
            del self.items[name]
            print(name, "removed from cart")
        else:
            print("Item not found")

    # Calculate total
    def total_price(self):
        total = sum(self.items.values())
        return total

    # 🔹 Display cart
    def display(self):
        print("\nCart Items:")
        for item, price in self.items.items():
            print(item, ":", price)


cart = ShoppingCart()

cart.add_item("Apple", 50)
cart.add_item("Milk", 30)
cart.add_item("Bread", 20)

cart.display()

print("Total:", cart.total_price())

cart.remove_item("Milk")

cart.display()
print("Total:", cart.total_price())

# 9. Write a Python program to create a class representing a stack data structure. Include methods for pushing, popping and displaying elements.

#  Stack class
class Stack:

    def __init__(self):
        self.items = []

    #  Push method (add element to stack)
    def push(self, item):
        self.items.append(item)
        print(item, "pushed into stack")

    #  Pop method (remove element from stack)
    def pop(self):
        if len(self.items) == 0:
            print("Stack is empty (Underflow)")
        else:
            removed = self.items.pop()
            print(removed, "popped from stack")

    #  Display method
    def display(self):
        if len(self.items) == 0:
            print("Stack is empty")
        else:
            print("Stack elements (top → bottom):")

            # Reverse list to show top first
            for item in reversed(self.items):
                print(item)


#  Create stack object
s = Stack()

#  Operations
s.push(10)
s.push(20)
s.push(30)

s.display()

s.pop()
s.display()

# 10. Write a Python program to create a class representing a queue data structure. Include methods for enqueueing and dequeueing elements.


# Queue class
class Queue:

    def __init__(self):
        self.items = []

    # Enqueue (add elements)
    def enqueue(self, item):
        self.items.append(item)
        print(item, "enqueued into queue")

    # Dequeue (remove element)
    def dequeue(self):
        # Check if queue is empty
        if len(self.items) == 0:
            print("Queue is empty (Underflow)")
        else:
            # Remove element from front (index 0)
            removed = self.items.pop(0)
            print(removed, "dequeued from queue")

    #  Display queue
    def display(self):
        if len(self.items) == 0:
            print("Queue is empty")
        else:
            print("Queue elements (front → rear):")
            for item in self.items:
                print(item)


# Create queue object
q = Queue()

#  Operations
q.enqueue(10)
q.enqueue(20)
q.enqueue(30)

q.display()

q.dequeue()
q.display()

# 11. Write a Python program to create a class representing a bank. Include methods for managing customer accounts and transactions.
# 	Create a Python class called BankAccount which represents a bank account, having as attributes: accountNumber (numeric type), name (name of the account owner as string type), balance.
# 	Create a constructor with parameters: accountNumber, name, balance.
# 	Create a Deposit() method which manages the deposit actions.
# 	Create a Withdrawal() method which manages withdrawals actions.
# 	Create an bankFees() method to apply the bank fees with a percentage of 5% of the balance account.
# 	Create a display() method to display account details. Give the complete code for the BankAccount class.

#  BankAccount class
class BankAccount:

    def __init__(self, accountNumber, name, balance):

        self.accountNumber = accountNumber   # account number (int)
        self.name = name                     # account holder name (string)
        self.balance = balance               # current balance

    #  Deposit method
    def Deposit(self, amount):
        # Add money to balance
        if amount > 0:
            self.balance += amount
            print(amount, "deposited successfully")
        else:
            print("Invalid deposit amount")

    #  Withdrawal method
    def Withdrawal(self, amount):
        # Check  enough balance is available or not
        if amount > self.balance:
            print("Insufficient balance")
        elif amount <= 0:
            print("Invalid withdrawal amount")
        else:
            self.balance -= amount
            print(amount, "withdrawn successfully")

    #  Bank Fees (5%)
    def bankFees(self):
        # Calculate 5% fee
        fee = self.balance * 0.05
        self.balance -= fee
        print("Bank fees applied:", fee)

    #  Display account details
    def display(self):
        print("\n--- Account Details ---")
        print("Account Number:", self.accountNumber)
        print("Account Holder:", self.name)
        print("Balance:", self.balance)


# Create object
acc = BankAccount(101, "sachin", 1000)

#  Perform operations
acc.display()

acc.Deposit(500)
acc.display()

acc.Withdrawal(300)
acc.display()

acc.bankFees()
acc.display()

# 12. Build a flashcard using class in python. A flashcard is a card having information on both sides, which can be used as an aid in memoization. Flashcards usually have a question on one side and an answer on the other.

# 	Example 1:

# 	Approach:

# 	Create a class named FlashCard.
# 	Initialize dictionary fruits using init() method. Here you have to define fruit name as key and it's color as value. E.g., {"Banana": "yellow", "Strawberries": "pink"}
# 	Now randomly choose a pair from fruits by using random module and store the key in variable fruit and value in variable color.
# 	Now prompt the user to answer the color of the randomly chosen fruit.
# 	If correct print correct else print wrong.
# 	Output:

# 	welcome to fruit quiz
# 	What is the color of Strawberries
# 	pink
# 	Correct answer
# 	Enter 0, if you want to play again: 0
# 	What is the color of watermelon
# 	green
# 	Correct answer
# 	Enter 0, if you want to play again: 1

import random   # used to pick random fruit

class FlashCard:

    def __init__(self):
        # dictionary: fruit -> color
        self.fruits = {
            "Banana": "yellow",
            "Strawberries": "pink",
            "Apple": "red",
            "Watermelon": "green",
            "Orange": "orange"
        }

    def play(self):
        print("Welcome to fruit quiz")

        while True:
            fruit, color = random.choice(list(self.fruits.items()))

            # ask question
            user_answer = input(f"What is the color of {fruit}? ")

            # check answer
            if user_answer.lower() == color.lower():
                print("Correct answer")
            else:
                print(f"Wrong answer. Correct is {color}")

            # ask to continue
            choice = input("Enter 0, if you want to play again: ")
            if choice != '0':
                break


# create object and start game
obj = FlashCard()
obj.play()

# 13. TechWorld, a technology training center, wants to allocate courses for instructors. An instructor is identified by name, technology skills, experience and average feedback. An instructor is allocated a course, if he/she satisfies the below two conditions:

# 	eligibility criteria:
# 	if experience is more than 3 years, average feedback should be 4.5 or more
# 	if experience is 3 years or less, average feedback should be 4 or more
# 	he/she should posses the technology skill for the course
# 	Identify the class name and attributes to represent instructors. Write a Python program to implement the class chosen with its attributes and methods.

# 	Note:

# 	Consider all instance variables to be private and methods to be public.
# 	An instructor may have multiple technology skills, so consider instance variable, technology_skill to be a list.
# 	check_eligibility(): Return true if eligibility criteria is satisfied by the instructor. Else, return false
# 	allocate_course(technology): Return true if the course which requires the given technology can be allocated to the instructor. Else, return false.
# 	Represent a few objects of the class, initialize instance variables using setter methods, invoke appropriate methods and test your program.

class Instructor:
    def __init__(self):
        self.__name = None
        self.__technology_skills = []
        self.__experience = 0
        self.__average_feedback = 0.0

    # Setter methods
    def set_name(self, name):
        self.__name = name

    def set_technology_skills(self, skills):
        self.__technology_skills = skills

    def set_experience(self, experience):
        self.__experience = experience

    def set_average_feedback(self, feedback):
        self.__average_feedback = feedback

    # Method to check eligibility
    def check_eligibility(self):
        if self.__experience > 3:
            if self.__average_feedback >= 4.5:
                return True
        else:
            if self.__average_feedback >= 4:
                return True
        return False

    # Method to allocate course
    def allocate_course(self, technology):
        if self.check_eligibility():
            if technology in self.__technology_skills:
                return True
        return False



# Instructor 1
inst1 = Instructor()
inst1.set_name("Rahul")
inst1.set_technology_skills(["Python", "Java"])
inst1.set_experience(5)
inst1.set_average_feedback(4.6)

print("Instructor 1 Eligible:", inst1.check_eligibility())
print("Can teach Python:", inst1.allocate_course("Python"))
print("Can teach C++:", inst1.allocate_course("C++"))


# Instructor 2
inst2 = Instructor()
inst2.set_name("Sneha")
inst2.set_technology_skills(["C", "C++"])
inst2.set_experience(2)
inst2.set_average_feedback(3.8)

print("\nInstructor 2 Eligible:", inst2.check_eligibility())
print("Can teach C++:", inst2.allocate_course("C++"))

# 14. Write a program that uses datetime module within a class. Enter manufacturing date and expiry date of the product. The program must display the years, months and days that are left for expiry.

from datetime import datetime

class Product:
    def __init__(self):
        self.__mfg_date = None
        self.__exp_date = None

    # Setter methods
    def set_mfg_date(self, date_str):
        self.__mfg_date = datetime.strptime(date_str, "%d-%m-%Y")

    def set_exp_date(self, date_str):
        self.__exp_date = datetime.strptime(date_str, "%d-%m-%Y")

    # Method to calculate remaining time
    def get_remaining_shelf_life(self):
        today = datetime.today()

        # difference between expiry date and today
        diff = self.__exp_date - today
        total_days = diff.days

        if total_days < 0:
            print("Product already expired ")
        else:
            years = total_days // 365
            remaining_days = total_days % 365
            months = remaining_days // 30
            days = remaining_days % 30

            print("Time left for expiry:")
            print(years, "years,", months, "months,", days, "days")



p1 = Product()
p1.set_mfg_date("01-01-2024")
p1.set_exp_date("01-06-2026")

p1.get_remaining_shelf_life()

# 15. A university wants to automate their admission process. Students are admitted based on the marks scored in the qualifying exam. A student is identified by student id, age and marks in qualifying exam. Data are valid, if:

# 	Age is greater than 20
# 	Marks is between 0 and 100 (both inclusive)
# 	A student qualifies for admission, if

# 	Age and marks are valid and
# 	Marks is 65 or more
# 	Write a python program to represent the students seeking admission in the university.


class Student:
    def __init__(self):
        self.__student_id = None
        self.__age = 0
        self.__marks = 0

    # Setter methods
    def set_student_id(self, sid):
        self.__student_id = sid

    def set_age(self, age):
        self.__age = age

    def set_marks(self, marks):
        self.__marks = marks

    # Method to check if data is valid
    def validate_data(self):
        if self.__age > 20 and 0 <= self.__marks <= 100:
            return True
        return False

    # Method to check admission eligibility
    def check_qualification(self):
        if self.validate_data():
            if self.__marks >= 65:
                return True
        return False

    # Display method
    def display(self):
        print("\nStudent ID:", self.__student_id)
        print("Age:", self.__age)
        print("Marks:", self.__marks)
        print("Valid Data:", self.validate_data())
        print("Eligible for Admission:", self.check_qualification())



# Student 1
s1 = Student()
s1.set_student_id(101)
s1.set_age(22)
s1.set_marks(75)

s1.display()

# Student 2
s2 = Student()
s2.set_student_id(102)
s2.set_age(19)
s2.set_marks(80)

s2.display()

# Student 3
s3 = Student()
s3.set_student_id(103)
s3.set_age(23)
s3.set_marks(60)

s3.display()

# 16. Ice-Cream Scoops and Bowl shop

# 	Create a class Scoop which has one public property flavor and one private proptery price. Take flavor values during object creation.

# 	Create a class Bowl with private prperty scoop_list which will have list of scoopd object.

# 	Create a method add_scoops in Bowl class which will add any no of Scoop objects given as parameter and store it in scoops_list.

# 	Make getter and setter method for price property.

# 	Make a method display to display flavour and price of each Scoop in scoop_list and print total price of the bowl by adding all flavour scoops prices.

# 	Make a method sold in both Scoop class and Bowl class to print no of quantity sold.


class Scoop:
    __sold_count = 0   # class variable to track sold scoops

    def __init__(self, flavor):
        self.flavor = flavor
        self.__price = 0
        Scoop.__sold_count += 1   # increase count when object created

    # Setter
    def set_price(self, price):
        self.__price = price

    # Getter
    def get_price(self):
        return self.__price

    # Sold method
    @classmethod
    def sold(cls):
        print("Total Scoops Sold:", cls.__sold_count)


class Bowl:
    __bowl_count = 0   # class variable to track bowls sold

    def __init__(self):
        self.__scoop_list = []
        Bowl.__bowl_count += 1

    # Method to add multiple scoops
    def add_scoops(self, *scoops):
        for scoop in scoops:
            self.__scoop_list.append(scoop)

    # Display method
    def display(self):
        total = 0
        print("\nScoops in Bowl:")

        for scoop in self.__scoop_list:
            print("Flavor:", scoop.flavor, "| Price:", scoop.get_price())
            total += scoop.get_price()

        print("Total Price of Bowl:", total)

    # Sold method
    @classmethod
    def sold(cls):
        print("Total Bowls Sold:", cls.__bowl_count)



# Create scoops
s1 = Scoop("Chocolate")
s1.set_price(50)

s2 = Scoop("Vanilla")
s2.set_price(40)

s3 = Scoop("Strawberry")
s3.set_price(60)

# Create bowl
b1 = Bowl()
b1.add_scoops(s1, s2, s3)

b1.display()

# Sold count
Scoop.sold()
Bowl.sold()

# 17. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

# Note: The bus seating capacity is 50. so the final fare amount should be 5500. You need to override the fare() method of a Vehicle class in Bus class.


class Vehicle:
    def __init__(self, capacity):
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100


class Bus(Vehicle):
    def __init__(self, capacity):
        super().__init__(capacity)

    # Overriding fare method
    def fare(self):
        base_fare = super().fare()
        maintenance = base_fare * 0.10
        total_fare = base_fare + maintenance
        return total_fare



bus = Bus(50)

print("Total Bus Fare:", bus.fare())

# 18. Write a Python class Employee with attributes like emp_id, emp_name, emp_salary, and emp_department and methods like calculate_emp_salary, emp_assign_department, and print_employee_details.

# 	Sample Employee Data:
# 	"ADAMS", "E7876", 50000, "ACCOUNTING"
# 	"JONES", "E7499", 45000, "RESEARCH"
# 	"MARTIN", "E7900", 50000, "SALES"
# 	"SMITH", "E7698", 55000, "OPERATIONS"

# 	Use 'assign_department' method to change the department of an employee.
# 	Use 'print_employee_details' method to print the details of an employee.
# 	Use 'calculate_emp_salary' method takes two arguments: salary and hours_worked, which is the number of hours worked by the employee. If the number of hours worked is more than 50, the method computes overtime and adds it to the salary. Overtime is calculated as following formula:
# 	overtime = hours_worked - 50
# 	Overtime amount = (overtime * (salary / 50))

class Employee:
    def __init__(self, name, emp_id, salary, department):
        self.__emp_name = name
        self.__emp_id = emp_id
        self.__emp_salary = salary
        self.__emp_department = department

    # Method to calculate salary with overtime
    def calculate_emp_salary(self, hours_worked):
        if hours_worked > 50:
            overtime = hours_worked - 50
            overtime_amount = overtime * (self.__emp_salary / 50)
            total_salary = self.__emp_salary + overtime_amount
        else:
            total_salary = self.__emp_salary

        return total_salary

    # Method to assign new department
    def assign_department(self, new_department):
        self.__emp_department = new_department

    # Method to display details
    def print_employee_details(self):
        print("\nEmployee ID:", self.__emp_id)
        print("Name:", self.__emp_name)
        print("Salary:", self.__emp_salary)
        print("Department:", self.__emp_department)


# Creating 4 employees
emp1 = Employee("ADAMS", "E7876", 50000, "ACCOUNTING")
emp2 = Employee("JONES", "E7499", 45000, "RESEARCH")
emp3 = Employee("MARTIN", "E7900", 50000, "SALES")
emp4 = Employee("SMITH", "E7698", 55000, "OPERATIONS")

# Change department for all employees
emp1.assign_department("HR")
emp2.assign_department("SALES")
emp3.assign_department("MARKETING")
emp4.assign_department("IT")

# Print details of all employees
emp1.print_employee_details()
emp2.print_employee_details()
emp3.print_employee_details()
emp4.print_employee_details()

# Calculate salary with overtime for all employees
print("\nSalary after overtime (emp1):", emp1.calculate_emp_salary(55))
print("Salary after overtime (emp2):", emp2.calculate_emp_salary(45))
print("Salary after overtime (emp3):", emp3.calculate_emp_salary(60))
print("Salary after overtime (emp4):", emp4.calculate_emp_salary(48))

# 19. Write a Python class Restaurant with attributes like menu_items, book_table, and customer_orders, and methods like add_item_to_menu, book_tables, and customer_order.

# 	Perform the following tasks now:

# 	Now add items to the menu.
# 	Make table reservations.
# 	Take customer orders.
# 	Print the menu.
# 	Print table reservations.
# 	Print customer orders.
# 	Note: Use dictionaries and lists to store the data.

class Restaurant:
    def __init__(self):
        self.menu_items = {}          # dictionary
        self.booked_tables = []       # list
        self.customer_orders = {}     # dictionary

    def add_item_to_menu(self, item, price):
        self.menu_items[item] = price

    def book_tables(self, table_number):
        self.booked_tables.append(table_number)

    def customer_order(self, customer_name, items):
        self.customer_orders[customer_name] = items

    def print_menu(self):
        print("\n--- MENU ---")
        for item, price in self.menu_items.items():
            print(item, ":", price)

    # Print  reservations
    def print_table_reservations(self):
        print("\n--- TABLE RESERVATIONS ---")
        for table in self.booked_tables:
            print("Table", table)

    # Print customer orders
    def print_customer_orders(self):
        print("\n--- CUSTOMER ORDERS ---")
        for customer, items in self.customer_orders.items():
            print(customer, "ordered:", items)


r = Restaurant()

# Add menu items
r.add_item_to_menu("Pizza", 250)
r.add_item_to_menu("Burger", 120)
r.add_item_to_menu("Pasta", 200)

# Book tables
r.book_tables(1)
r.book_tables(3)

# Customer orders
r.customer_order("Rahul", ["Pizza", "Burger"])
r.customer_order("Sneha", ["Pasta"])

# Display all
r.print_menu()
r.print_table_reservations()
r.print_customer_orders()

# 20. Write a Python class BankAccount with attributes like account_number, balance, date_of_opening and customer_name, and methods like deposit, withdraw, and check_balance.


class BankAccount:
    def __init__(self, acc_no, name, balance, date):
        self.__account_number = acc_no
        self.__customer_name = name
        self.__balance = balance
        self.__date_of_opening = date

    # Deposit method
    def deposit(self, amount):
        self.__balance += amount
        print(amount, "deposited successfully")

    # Withdraw method
    def withdraw(self, amount):
        if amount <= self.__balance:
            self.__balance -= amount
            print(amount, "withdrawn successfully")
        else:
            print("Insufficient balance ❌")

    # Check balance
    def check_balance(self):
        print("Current Balance:", self.__balance)

    # Display account details
    def display_details(self):
        print("\nAccount Number:", self.__account_number)
        print("Customer Name:", self.__customer_name)
        print("Balance:", self.__balance)
        print("Date of Opening:", self.__date_of_opening)



acc1 = BankAccount(101, "Rahul", 5000, "01-01-2024")

acc1.display_details()

acc1.deposit(2000)
acc1.withdraw(3000)
acc1.check_balance()

# 21. Write a Python class Inventory with attributes like item_id, item_name, stock_count, and price, and methods like add_item, update_item, and check_item_details.

class Inventory:
    def __init__(self):
        self.__item_id = None
        self.__item_name = None
        self.__stock_count = 0
        self.__price = 0

    # Add item
    def add_item(self, item_id, name, stock, price):
        self.__item_id = item_id
        self.__item_name = name
        self.__stock_count = stock
        self.__price = price
        print("Item added successfully ✅")

    # Update item (stock and price)
    def update_item(self, stock=None, price=None):
        if stock is not None:
            self.__stock_count = stock
        if price is not None:
            self.__price = price
        print("Item updated successfully 🔄")

    # Check item details
    def check_item_details(self):
        print("\n--- Item Details ---")
        print("Item ID:", self.__item_id)
        print("Item Name:", self.__item_name)
        print("Stock Count:", self.__stock_count)
        print("Price:", self.__price)



item1 = Inventory()

# Add item
item1.add_item(101, "Laptop", 10, 50000)

# Display details
item1.check_item_details()

# Update item
item1.update_item(stock=15, price=52000)

# Display updated details
item1.check_item_details()