# -*- coding: utf-8 -*-
"""Python-Challenges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTG9SWpSJ_yGCC9X73UL7F0c3MJZ4fQH
"""

#  Challenge: Student Marks Analyzer

# Create a Python program that allows a user to input student names along with their marks and then calculates useful statistics.
# Your program should:
# 1. Let the user input multiple students with their marks (name + integer score).
# 2. After input is complete, display:
#    - Average marks
#    - Highest marks and student(s) who scored it
#    - Lowest marks and student(s) who scored it
#    - Total number of students

# Bonus:
# - Allow the user to enter all data first, then view the report
# - Format output clearly in a report-style layout
# - Prevent duplicate student names

def student_marks_analyzer():
    students = {}   # dictionary to store name: marks

    print(" Student Marks Entry ")

    while True:
        name = input("Enter student name (or type 'done' to finish): ").strip()

        if name.lower() == 'done':
            break

        # Prevent duplicate names
        if name in students:
            print(" Student already exists! Try a different name.")
            continue

        try:
            marks = int(input("Enter marks: "))
            students[name] = marks
        except ValueError:
            print("Invalid input! Marks must be an integer.")

    # If no data entered
    if len(students) == 0:
        print("\nNo student data entered.")
        return

    # Calculations
    total_students = len(students)
    total_marks = sum(students.values())
    average = total_marks / total_students

    highest_marks = max(students.values())
    lowest_marks = min(students.values())

    # Find students with highest and lowest marks
    highest_students = []
    lowest_students = []

    for name, marks in students.items():
        if marks == highest_marks:
            highest_students.append(name)
        if marks == lowest_marks:
            lowest_students.append(name)

    # Report
    print("\n Student Marks Report ")
    print(f"Total Students : {total_students}")
    print(f"Average Marks  : {average:.2f}")

    print(f"\nHighest Marks  : {highest_marks}")
    print("Topper(s)      :", ", ".join(highest_students))

    print(f"\nLowest Marks   : {lowest_marks}")
    print("Lowest Scorer(s):", ", ".join(lowest_students))



# Run program
student_marks_analyzer()

#  Challenge: CLI Contact Book (CSV-Powered)

# Create a terminal-based contact book tool that stores and manages contacts using a CSV file.

# Your program should:
# 1. Ask the user to choose one of the following options:
#    - Add a new contact
#    - View all contacts
#    - Search for a contact by name
#    - Exit
# 2. Store contacts in a file called `contacts.csv` with columns:
#    - Name
#    - Phone
#    - Email
# 3. If the file doesn't exist, create it automatically.
# 4. Keep the interface clean and clear.

# Example:
# Add Contact
# View All Contacts
# Search Contact
# Exit

# Bonus:
# - Format the contact list in a table-like view
# - Allow partial match search
# - Prevent duplicate names from being added


import csv
import os

FILE_NAME = "contacts.csv"

# Step 1: Create file if not exists
def initialize_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, mode='w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Name", "Phone", "Email"])  # header


# Step 2: Add Contact
def add_contact():
    name = input("Enter Name: ").strip()

    # Check duplicate
    if contact_exists(name):
        print(" Contact already exists!")
        return

    phone = input("Enter Phone: ").strip()
    email = input("Enter Email: ").strip()

    with open(FILE_NAME, mode='a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([name, phone, email])

    print(" Contact added successfully!")


# Step 3: View All Contacts
def view_contacts():
    with open(FILE_NAME, mode='r') as file:
        reader = csv.reader(file)
        data = list(reader)

        if len(data) <= 1:
            print("No contacts found.")
            return

        print("\n Contact List:")
        print("-" * 40)

        for row in data:
            print(f"{row[0]:15} | {row[1]:12} | {row[2]}")

        print("-" * 40)


# Step 4: Search Contact (partial match)
def search_contact():
    keyword = input("Enter name to search: ").strip().lower()

    found = False

    with open(FILE_NAME, mode='r') as file:
        reader = csv.reader(file)
        next(reader)  # skip header

        for row in reader:
            if keyword in row[0].lower():
                print(f"Found: {row[0]} | {row[1]} | {row[2]}")
                found = True

    if not found:
        print(" No matching contact found.")


# Step 5: Check Duplicate
def contact_exists(name):
    with open(FILE_NAME, mode='r') as file:
        reader = csv.reader(file)
        next(reader)

        for row in reader:
            if row[0].lower() == name.lower():
                return True
    return False


# Step 6: Menu System
def main():
    initialize_file()

    while True:
        print("\n=== Contact Book ===")
        print("1. Add Contact")
        print("2. View All Contacts")
        print("3. Search Contact")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            add_contact()
        elif choice == '2':
            view_contacts()
        elif choice == '3':
            search_contact()
        elif choice == '4':
            print("Exiting...")
            break
        else:
            print(" Invalid choice!")


# Run Program
main()

# Challenge:  Personal Movie Tracker with JSON

# Create a Python CLI tool that lets users maintain their own personal movie database, like a mini IMDb.

# Your program should:
# 1. Store all movie data in a `movies.json` file.
# 2. Each movie should have:
#    - Title
#    - Genre
#    - Rating (out of 10)
# 3. Allow the user to:
#    - Add a movie
#    - View all movies
#    - Search movies by title or genre
#    - Exit the app

# Bonus:
# - Prevent duplicate titles from being added
# - Format output in a clean table
# - Use JSON for reading/writing structured data

import json
import os

FILE_NAME = "movies.json"

# Step 1: Initialize file
def initialize_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, 'w') as file:
            json.dump([], file)   # empty list


# Step 2: Load data
def load_movies():
    with open(FILE_NAME, 'r') as file:
        return json.load(file)


# Step 3: Save data
def save_movies(movies):
    with open(FILE_NAME, 'w') as file:
        json.dump(movies, file, indent=4)


# Step 4: Add Movie
def add_movie():
    movies = load_movies()

    title = input("Enter movie title: ").strip()

    # Prevent duplicate
    for movie in movies:
        if movie['title'].lower() == title.lower():
            print(" Movie already exists!")
            return

    genre = input("Enter genre: ").strip()

    try:
        rating = float(input("Enter rating (out of 10): "))
    except ValueError:
        print(" Invalid rating!")
        return

    new_movie = {
        "title": title,
        "genre": genre,
        "rating": rating
    }

    movies.append(new_movie)
    save_movies(movies)

    print("Movie added successfully!")


# Step 5: View Movies
def view_movies():
    movies = load_movies()

    if not movies:
        print("No movies found.")
        return

    print("\n Movie List")
    print("-" * 50)

    for movie in movies:
        print(f"{movie['title']:20} | {movie['genre']:15} | {movie['rating']}")

    print("-" * 50)


# Step 6: Search Movies
def search_movies():
    movies = load_movies()

    keyword = input("Enter title or genre: ").strip().lower()
    found = False

    for movie in movies:
        if (keyword in movie['title'].lower() or
            keyword in movie['genre'].lower()):

            print(f"Found: {movie['title']} | {movie['genre']} | {movie['rating']}")
            found = True

    if not found:
        print(" No matching movie found.")


# Step 7: Menu
def main():
    initialize_file()

    while True:
        print("\n=== Movie Tracker ===")
        print("1. Add Movie")
        print("2. View Movies")
        print("3. Search Movies")
        print("4. Exit")

        choice = input("Enter choice: ")

        if choice == '1':
            add_movie()
        elif choice == '2':
            view_movies()
        elif choice == '3':
            search_movies()
        elif choice == '4':
            print("Goodbye!")
            break
        else:
            print("Invalid choice!")


# Run program
main()

#  Challenge: Real-Time Weather Logger (API + CSV)

# Build a Python CLI tool that fetches real-time weather data for a given city and logs it to a CSV file for daily tracking.

# Your program should:
# 1. Ask the user for a city name.
# 2. Fetch weather data using the OpenWeatherMap API.
# 3. Store the following in a CSV file (`weather_log.csv`):
#    - Date (auto-filled as today's date)
#    - City
#    - Temperature (in °C)
#    - Weather condition (e.g., Clear, Rain)
# 4. Prevent duplicate entries for the same city on the same day.
# 5. Allow users to:
#    - Add new weather log
#    - View all logs
#    - Show average, highest, lowest temperatures, and most frequent condition

# Bonus :
# - Format the output like a table
# - Handle API failures and invalid city names gracefully



import requests
import csv
import os
from datetime import datetime
from collections import Counter

API_KEY = "dd402ba0f5b7556d2952e49052c026ad"   # Replace with your OpenWeatherMap API key
FILE_NAME = "weather_log.csv"


# Step 1: Initialize CSV file
def initialize_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "City", "Temperature", "Condition"])


# Step 2: Fetch Weather Data
def fetch_weather(city):
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

    try:
        response = requests.get(url)
        data = response.json()

        if response.status_code != 200:
            print("City not found or API error.")
            return None

        temp = data['main']['temp']
        condition = data['weather'][0]['main']

        return temp, condition

    except requests.exceptions.RequestException:
        print(" Network error. Please try again.")
        return None


# Step 3: Check Duplicate Entry
def is_duplicate(date, city):
    if not os.path.exists(FILE_NAME):
        return False

    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        next(reader)

        for row in reader:
            if row[0] == date and row[1].lower() == city.lower():
                return True
    return False


# Step 4: Add Weather Log
def add_weather_log():
    city = input("Enter city name: ").strip()
    date = datetime.now().strftime("%Y-%m-%d")

    if is_duplicate(date, city):
        print("Weather already logged for this city today.")
        return

    result = fetch_weather(city)

    if result:
        temp, condition = result

        with open(FILE_NAME, 'a', newline='') as file:
            writer = csv.writer(file)
            writer.writerow([date, city, temp, condition])

        print("Weather logged successfully!")


# Step 5: View Logs
def view_logs():
    if not os.path.exists(FILE_NAME):
        print("No logs found.")
        return

    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        data = list(reader)

        if len(data) <= 1:
            print("No logs available.")
            return

        print("\n Weather Log")
        print("-" * 50)

        for row in data:
            print(f"{row[0]:12} | {row[1]:15} | {row[2]:10} | {row[3]}")  #  row[0] → Date | row[1] → City | row[2] → Temperature | row[3] → Condition

        print("-" * 50)


# Step 6: Statistics
def show_statistics():
    if not os.path.exists(FILE_NAME):
        print("No data available.")
        return

    temps = []
    conditions = []

    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        next(reader)

        for row in reader:
            temps.append(float(row[2]))
            conditions.append(row[3])

    if not temps:
        print("No data to analyze.")
        return

    avg_temp = sum(temps) / len(temps)
    max_temp = max(temps)
    min_temp = min(temps)
    common_condition = Counter(conditions).most_common(1)[0][0]

    print("\n Weather Statistics")
    print(f"Average Temp : {avg_temp:.2f}°C")
    print(f"Highest Temp : {max_temp}°C")
    print(f"Lowest Temp  : {min_temp}°C")
    print(f"Most Frequent Condition : {common_condition}")


# Step 7: Menu
def main():
    initialize_file()

    while True:
        print("\n Weather Logger ")
        print("1. Add Weather Log")
        print("2. View Logs")
        print("3. Show Statistics")
        print("4. Exit")

        choice = input("Enter choice: ")

        if choice == '1':
            add_weather_log()
        elif choice == '2':
            view_logs()
        elif choice == '3':
            show_statistics()
        elif choice == '4':
            print(" Exiting...")
            break
        else:
            print(" Invalid choice!")


# Run Program
main()